### ISSUE TITLE
auto_paint filter not working | CraigslistForSale 'CTA' category

### ISSUE THREAD

**Issue by Quresh95** [juliomalegria/python-craigslist#100]
The filter, auto_paint, under the CTA (cars & trucks) category in CraigslistForSale is not working. I believe it is because the filter has been changed to 'paint color' on craigslist. I am a novice hobby coder so am unfamiliar with how to implement the change myself.

**Comment by irahorecka** [comment]
Hey @Quresh95, I submitted a PR to address this issue. You can clone this version and see if it works for your situation. Here's as short [article](https://dev.to/bolajiayodeji/how-to-test-a-pull-request-locally-before-merging-1h29) on how to clone a PR.

**Comment by juliomalegria** [comment]
This was fixed by @irahorecka's wonderful PR (#98) that was just merged. There's a new version on PyPI with this fix :)

**Comment by Quresh95** [comment]
Amazing thank you!
