### ISSUE TITLE
min/max mileage filter not working

### ISSUE THREAD

**Issue by Quresh95** [juliomalegria/python-craigslist#101]
The filter, min_mileage & max_mileage, under the CTA (cars & trucks) category in CraigslistForSale is not working.

**Comment by irahorecka** [comment]
Likewise for this issue (referencing issue #100)

**Comment by juliomalegria** [comment]
Hi @Quresh95. Can you explain me what issue you're having with the filters? The correct names for the filters are `min_miles` and `max_miles`. That might be the issue.

I did a quick test and it seems to be working correctly for me:

```python
>>> from craigslist import CraigslistForSale
>>> cl_fs = CraigslistForSale(site='sfbay', category='cta', filters={'min_miles': 400000, 'max_miles': 450000})
>>> len(list(cl_fs.get_results()))
18
```

From the website:

![Screen Shot 2020-12-19 at 11 34 06 PM](https://user-images.githubusercontent.com/1008637/102701809-56c2db80-425b-11eb-9da2-296564919f58.png)

**Comment by Quresh95** [comment]
Agreed, I actually had the correct names in my code, min_miles & max_miles. They didn't seem to be working earlier but worked fine just now. I must've had something else wrong with my code which I seem to have since resolved. Thank you!
