### ISSUE TITLE
An idea: Add filter for owner or dealer listing for certain for sale categories

### ISSUE THREAD

**Issue by Quresh95** [juliomalegria/python-craigslist#103]
In CraigslistForSale, there are several categories (e.g. 'CTA') that have the option to filter listings by dealer or owner on the website. 

Adding that as a filter in this would be very useful.

**Comment by irahorecka** [comment]
Hey @Quresh95, rather than setting `category='cta'`, try `category='cto'` for listings by owner, and `category='ctd'` for listings by dealer.

**Comment by Quresh95** [comment]
Thank you @irahorecka for the insight! I will use that as a reference going forward. Apologies, I am a hobby coder and am overcoming a bit of an initial learning curve

**Comment by Quresh95** [comment]
Thank you @irahorecka for the insight! I will use that as a reference going forward. Apologies, I am a hobby coder and am overcoming a bit of an initial learning curve

**Comment by irahorecka** [comment]
No problem, @Quresh95 - happy to help.

**Comment by irahorecka** [comment]
Hey, @Quresh95 - if you are practicing web scraping / data science with this library, I wrote another library to work closely with python-craigslist to allow high-throughput queries (https://github.com/irahorecka/python-craigslist-meta)
