### ISSUE TITLE
'housing_type' and 'laundry' filters

### ISSUE THREAD

**Issue by jackdbastian** [juliomalegria/python-craigslist#107]
Are the 'housing_type' and 'laundry' filters still supported?  They both return "not a valid filter".

**Comment by irahorecka** [comment]
Hey @jackdbastian, could you provide the code snippet that raised this issue? I couldn't replicate it.

```python
from craigslist import CraigslistHousing

apts_sfbay = CraigslistHousing(
    site="sfbay",
    category="apa",
    filters={"housing_type": "apartment", "laundry": "w/d hookups"},
)
print(next(apts_sfbay.get_results()))
```

**Comment by jackdbastian** [comment]
Hi @irahorecka, I'm not sure what I was doing wrong before but your snippet worked.  Thank you for the help and for maintaining this awesome package!

**Comment by irahorecka** [comment]
@jackdbastian no problem, happy to help

**Comment by irahorecka** [comment]
Hey @jackdbastian, I created a new python craigslist api library that might be of interest (https://github.com/irahorecka/pycraigslist).
