### ISSUE TITLE
Number of bedrooms?

### ISSUE THREAD

**Issue by shahesam84** [juliomalegria/python-craigslist#110]
Thanks for this great work. Is there any filter for the number of bedrooms? Are you willing to expand the filter criteria options? Thanks

**Comment by irahorecka** [comment]
Hi @shahesam84, by "filter for the number of bedrooms" do you mean setting filter keys for minimum and maximum bedrooms? If so, you can do this:

```python
from craigslist import CraigslistHousing

three_bdrms = CraigslistHousing(site="sfbay", filters={"min_bedrooms": 3, "max_bedrooms": 3})
for post in three_bdrms.get_results(limit=5):
    print(post)
```

**Comment by shahesam84** [comment]
Yes, that's exactly what I want. I will have a look and let you know.
