### ISSUE TITLE
release new version with p.text fix

### ISSUE THREAD

**Issue by christopherbaek** [juliomalegria/python-craigslist#19]
Can you publish a new version with this fix: https://github.com/juliomalegria/python-craigslist/commit/ebd99b5bc7afe9edb87bbe73843193dfdcfa1750

**Comment by juliomalegria** [comment]
Hi there, yes. Sorry about that.
I want to merge branch `list-filters` (from #15), and then I'll release a new version. I'll do it ASAP (hopefully today).

**Comment by christopherbaek** [comment]
Awesome, thanks!

**Comment by juliomalegria** [comment]
New version (v1.0.2) was just released to PyPI! Sorry for the delay :)
