### ISSUE TITLE
1.0.2 

### ISSUE THREAD

**Issue by cyn1cal** [juliomalegria/python-craigslist#22]
upon releasing 1.0.2 you got rid of the filter tree you had? I saw some type of tree you had and was referencing it for what filters to apply.

would appreciate it if you re-added it to the help or sent me in the right direction

thanks alot as always!

**Comment by juliomalegria** [comment]
Hey there,
I removed the filter tree, and changed it to a class-method called show_fiters, which will show you all of the filters that a subclass has. For example:

```
from craigslist import CraigslistJobs
>>> CraigslistJobs.show_filters()
```

However, you can still see the filter tree by looking at the README file in the old version ([link here](https://github.com/juliomalegria/python-craigslist/blob/fecd75b8b2b34a59c9ca4debcc9f864d72dd1ac0/README.rst)).
