### ISSUE TITLE
Searching for key words in a title

### ISSUE THREAD

**Issue by gregv21v** [juliomalegria/python-craigslist#24]
How do you search for key words in the title of an ad using the filter parameter?

**Comment by juliomalegria** [comment]
Hi Gregory,

To do that, you'll use ['query'](https://github.com/juliomalegria/python-craigslist/blob/master/craigslist/__init__.py#L62) and ['search_titles'](https://github.com/juliomalegria/python-craigslist/blob/master/craigslist/__init__.py#L63). E.g.:

    (..., filters={'query': 'spacious', 'search_titles': True})

I'll try to improve the documentation to include an example of this.
