### ISSUE TITLE
No longer works?

### ISSUE THREAD

**Issue by Bazhunga** [juliomalegria/python-craigslist#31]
As of today it looks like the wrapper no longer returns results. I've been running it for the past week and it's been fine until now. Is it an issue on my end?

**Comment by bdubayah** [comment]
I'm having this problem as well. I'd be happy to provide any configuration information.

**Comment by dacox** [comment]
@Bazhunga @bdubayah see #30 

It seems to work for me after applying this patch. Cheers!

**Comment by juliomalegria** [comment]
Hi Bazhunga, I've fixed this in 403da28. I'll do a new PyPI release right now.
