### ISSUE TITLE
API Broken

### ISSUE THREAD

**Issue by gregv21v** [juliomalegria/python-craigslist#32]
Is there something broken with the API? Whenever I "get_results", it returns nothing.

**Comment by juliomalegria** [comment]
Hi Gregory,
Seems like Craigslist recently changed its HTML format and the library stopped working (see #31). I've already fixed it and released a new version to PyPI.
Please update your library, make sure your version is 1.0.3 (or higher). Feel free to reopen this issue if this doesn't fix your problem.

**Comment by gregv21v** [comment]
I'm updated to 1.0.3, and I'm still having the issue.

Here is what I'm trying to run:

`from craigslist import CraigslistHousing
cl_e = CraigslistHousing(site='boston')

for result in cl_e.get_results(limit=5):
    print(result)`

**Comment by gregv21v** [comment]
Something happened. It works now. I'm not sure what it was. Maybe the update did work afterall.
