### ISSUE TITLE
craigslist areas / categories reference json api

### ISSUE THREAD

**Issue by AlJohri** [juliomalegria/python-craigslist#35]
instead (or perhaps in addition to) using http://www.craigslist.org/about/sites, you can also use the craigslist reference json api: http://www.craigslist.org/about/reference

areas: http://reference.craigslist.org/Areas
categories: http://reference.craigslist.org/Categories

**Comment by SophiaJia** [comment]
I am trying to get cleveland. http://reference.craigslist.org/Areas/27
looks like it works on craigslist but doesn't work with the code. and I am wondering why. the test code works well  thought
