### ISSUE TITLE
Save print result to data set 

### ISSUE THREAD

**Issue by SophiaJia** [juliomalegria/python-craigslist#36]
Hi @juliomalegria  , How can I save the result in to a data format, that I can output the data?

thanks 
Sophia

**Comment by juliomalegria** [comment]
Hi Sophia,
Not sure if I understand your question. The method `get_results` returns an iterator of all the results. You can then save those results in whatever data format, like for example, JSON. Here an example:

```
import json
import craigslist

# ...
for result in cl_h.get_results(...):
    # Dump result (dictionary) into a JSON object and do something with it
    json.dumps(result)  # ...
```

Let me know if this answers your question.
