### ISSUE TITLE
Not getting geotags?

### ISSUE THREAD

**Issue by Bazhunga** [juliomalegria/python-craigslist#38]
It seems that all returned data under forsale has a geotag field of "null". Did craigslist change recently?

**Comment by juliomalegria** [comment]
Hi Kevin. It seems that recently CL is adding the 'map' tag for all entries, even if the post doesn't have a location. However, the entries that do have a location will be populated if `geotagged=True`. If you see results with `geotag: None` it probably means that they just don't have a location.

If you find an entry that does have a location in CL, but the result didn't populate the geotag, let me know, and I'll look into it.
