### ISSUE TITLE
Reading the post description

### ISSUE THREAD

**Issue by pierreTklein** [juliomalegria/python-craigslist#40]
Hi,
I was wondering if there was functionality to get the description of a given post within the module?
Thanks!

**Comment by juliomalegria** [comment]
Hi Pierre. The library doesn't have functionality yet, but we'll have it soon. In fact, there's already a pull request for that (#45).

**Comment by NinjaEngineer** [comment]
I would also like this feature.

**Comment by juliomalegria** [comment]
Hey @pierreTklein. I've just merged the pull request #45. I'm going to do a release right now, and this functionality will be available. Sorry for the delay!

**Comment by juliomalegria** [comment]
New version release (`1.0.6`) including these changes!
