### ISSUE TITLE
.show_filters() not working

### ISSUE THREAD

**Issue by lanewinfield** [juliomalegria/python-craigslist#42]
```
>>> from craigslist import CraigslistJobs
>>> CraigslistJobs.show_filters()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'CraigslistJobs' has no attribute 'show_filters'
```

**Comment by lanewinfield** [comment]
I think this was caused by CL blocking specific IPs (in this case, one from DigitalOcean). Was able to get this working on my local device though.

**Comment by lanewinfield** [comment]
Nevermind. Looks like it's still an issue. My local machine has no problem doing it, but both a local network raspberry pi as well as my DO droplet seem unable to both read show_filters OR run any parts of the script.

**Comment by juliomalegria** [comment]
Odd. Could it be that they don't have the latest version of python-craigslist? Can you run `pip list` and paste the output? List filters were added in version=1.0.2.
