### ISSUE TITLE
Unclear what filter values should be

### ISSUE THREAD

**Issue by andreking** [juliomalegria/python-craigslist#43]
Is the filter "bathrooms" supposed to be an integer or a list? Also confused about "query", is it a string or perhaps a dict?

**Comment by juliomalegria** [comment]
Almost all filters follow the same format as their counter parts in the CL website. So bathrooms is a number (same as the website), and query is a string, e.g. "iphone 6 32gb".

**Comment by juliomalegria** [comment]
Take a look at the examples in the documentation (README.md) to understand how to use the filters. Let me know if you have other doubts :)
