### ISSUE TITLE
Results from wrong location

### ISSUE THREAD

**Issue by amd112** [juliomalegria/python-craigslist#49]
Easy to deal with by filtering externally, but might be worth thinking about searches with few results. 

For housing, small markets tend to have few listings so searches like CraigslistHousing(site='stillwater', category='apa', filters={'posted_today': True}) will return housing from all over Oklahoma, as scraped from the 'similar listings' section. 

This may be applicable for job or sale searches as well, where results to similar queries are shown when there are few or no results.

**Comment by juliomalegria** [comment]
Thanks Ann for pointing that out! I hadn't realize this behavior. I've fixed this, and will do a new release with the fix soon.
