### ISSUE TITLE
sites.py does not parse properly. 

### ISSUE THREAD

**Issue by chikenlegg** [juliomalegria/python-craigslist#5]
Assuming due to an update in CL. All that was needed was an extra '/' in rsplit. 

!OLD 
site = a.attrs['href'].rsplit('/', 1)[1].split('.')[0]

!NEW 
site = a.attrs['href'].rsplit('//', 1)[1].split('.')[0]

Works now :)

**Comment by juliomalegria** [comment]
Thanks for pointing that out!
Would you be interested in doing the change in a fork and opening a pull request? If not, I'll do the change as soon as possible.

**Comment by juliomalegria** [comment]
Fixed in #7
