### ISSUE TITLE
CraigslistForSale does not actually support auto_transmission filter

### ISSUE THREAD

**Issue by ds89snsadbf** [juliomalegria/python-craigslist#51]
Was reading through your code and I saw in your readme, it says `auto_transmission` is a filter you can pass to car searches, however that option isnt available

**Comment by juliomalegria** [comment]
`auto_transmission`, as well as other category specific filters are obtained from scrapping the site. That's why you couldn't find it in the code.

All the filters that show when you run `CraigslistForSale.show_filters(category='cta')` should be supported.

**Comment by ds89snsadbf** [comment]
``` 
CraigslistForSale(site='sfbay', category='cta', filters={'query': 'Honda', 'auto_transmission': 'manual'})
'm' is not a valid option for auto_transmission
'a' is not a valid option for auto_transmission
'n' is not a valid option for auto_transmission
'u' is not a valid option for auto_transmission
'a' is not a valid option for auto_transmission
'l' is not a valid option for auto_transmission
```


```
CraigslistForSale(site='sfbay', category='cta', filters={'query': 'Honda', 'auto_transmission': 1})
'1' is not a valid option for auto_transmission
'1' is not a valid option for auto_transmission
```

**Comment by juliomalegria** [comment]
See 2nd example in "Examples" for a query using category-specific filters. 

`CraigslistForSale(site='sfbay', category='cta', filters={'query': 'Honda', 'auto_transmission': ['manual']})` should do the trick (i.e. put 'manual' in a list).
