### ISSUE TITLE
Craigslist categories.  

### ISSUE THREAD

**Issue by abwillingham** [juliomalegria/python-craigslist#56]
Where can one get a list of categories?

**Comment by dsnvwlmnt** [comment]
On the main Craigslist page, if I understand the question correctly. Hovering over each will show you the name that's used in the code.

![image](https://user-images.githubusercontent.com/14173022/46252889-3614ce00-c424-11e8-9bac-060c236b8b58.png)

**Comment by juliomalegria** [comment]
Thanks @abwillingham for the question, and thanks @dsnvwlmnt for the explanation.
This is a valid question, so I've added a section in the README to answer it: https://github.com/juliomalegria/python-craigslist#where-to-get-category-from
