### ISSUE TITLE
neighborhoods filter

### ISSUE THREAD

**Issue by mbettan** [juliomalegria/python-craigslist#59]
Hello guys,

Any ideas how we can filter using neighborhoods? It looks like not supported, correct?

Thanks

**Comment by coperyan** [comment]
You can't add a filter before you search. You can access the "where" attribute of the search result, this shows neighborhoods.

**Comment by juliomalegria** [comment]
Hey @mbettan, to filter by neighborhood you could either:

* Use the "MILES FROM ZIP", specifying the `search_distance` + `zip_code` in the `filters`.
* Use `query='<neighborhood>'`

Those 2 would be pre-query filters. The other option, as @coperyan said, is to post-query filter the result based on the `where` attribute, that contains the name of the neighborhood.
