### ISSUE TITLE
geotags

### ISSUE THREAD

**Issue by irahorecka** [juliomalegria/python-craigslist#64]
Hello, I set geotagged = True for housing, but I receive all 'geotag': None. These websites usually have maps and an address underneath. Is this a CL issue?

**Comment by calvinized** [comment]
Same issue here, must be a change on CL side

**Comment by irahorecka** [comment]
Darn, tons of cool things could be done with that information

**Comment by echentw** [comment]
Yeah, I had this problem too. Here's the PR to fix it in the python-craigslist dependency: https://github.com/juliomalegria/python-craigslist/pull/65

As a workaround for now, you can make those changes manually in your local python-craigslist.

**Comment by juliomalegria** [comment]
Hi Ira. This was fixed with #65. Thanks @echentw !
