### ISSUE TITLE
Max get_results 

### ISSUE THREAD

**Issue by irahorecka** [juliomalegria/python-craigslist#66]
I did some testing, and it seems like the maximum get_results per site, area, and category is 3000.

e.g.
`
from craigslist import CraigslistHousing
x = CraigslistHousing(site='sfbay',category='apa',area='eby')
y = [i for i in x.get_results(sort_by='newest')]

print(len(y)) #3000
`

Would you say Craigslist has an upper limit on posts per area in a certain category?

**Comment by irahorecka** [comment]
Hello, just a follow up.... <br>
![alt text](https://i.imgur.com/Nawj4GG.png)<br><br>
A heads up for future users... Craigslist caps max search per region at <b>3000</b>. <br>
I will close this issue.

**Comment by juliomalegria** [comment]
Thanks Ira. I hadn't notice that. I'll add it to the documentation.
