### ISSUE TITLE
Alerts are 10-15 minutes late

### ISSUE THREAD

**Issue by damanc7** [juliomalegria/python-craigslist#77]
There seems to be a 10-15 minute delay from when something is posted on craigslist to when python-craigslist finds it. Is there any way to minimize this time?

**Comment by irahorecka** [comment]
I think this is a Craigslist feature. I post items on the website frequently and the delay you’re talking about is a common phenomenon.

**Comment by damanc7** [comment]
> I think this is a Craigslist feature. I post items on the website frequently and the delay you’re talking about is a common phenomenon.
> […](#)

Is there a way around this? I’ve applied for a gig 10 minutes after it was posted and it was already filled by 3 other people so I think craigslist is posting within this time.

**Comment by juliomalegria** [comment]
What if you check the `posted_today` filter? Just spitballing, I don't know the Craigslist internals, so not sure if that would work, but maybe that makes Craigslist get the newest posts?

**Comment by damanc7** [comment]
I tested by going through Selenium and refreshing the page over and over (as a user would) and am still getting the delay so it's with Craigslist.  I am going to close the issue as it isn't with python-Craigslist.
