### ISSUE TITLE
site.py doesn't work.

### ISSUE THREAD

**Issue by bus710** [juliomalegria/python-craigslist#8]
Hi,

I am very glad to find this package!
Because now I am trying to find an apartment in SoCal area, this package is really helpful for me.

Btw, when I try to use your example, unfortunately, it doesn't work because site.py couldn't get decent data from craigslist so that I just commented a line from '__init__' and then now it works perfectly as I expected [1]. If you have time to revise it, this can be considered.

Thanks!
SJ

[1] line 66 (#raise ValueError(msg))

**Comment by juliomalegria** [comment]
The issue with the `sites.py` has already been fixed. I just hadn't had the time to make a new release. I'll do that pretty soon.
Thanks for using the module! :+1:

**Comment by bus710** [comment]
You are the best! :+1:

**Comment by sjohns0828** [comment]
Has this issue been resolved? I am trying to use CraigslistForSale and am getting the following error

ValueError: 'detroit' is not a valid site

After doing some investigating it seems that all sites are not properly loaded. Thanks for any help!

**Comment by juliomalegria** [comment]
New version of python-craigslist (1.0.1) is live in PyPI now. That version should fix this issue.

Thanks for bearing with me :)
