### ISSUE TITLE
ImportError: No module named 'Queue'

### ISSUE THREAD

**Issue by Superbest** [juliomalegria/python-craigslist#9]
`  File "C:\Python34\lib\site-packages\craigslist\__init__.py", line 3, in <module>
    from Queue import Queue
ImportError: No module named 'Queue'`

Looks like it's not Python3 compatible after all.

**Comment by juliomalegria** [comment]
The issue has already been fixed. I just hadn't had the time to make a new release yet. I'll do that pretty soon.
Thanks for using the module! :+1:

**Comment by xilni** [comment]
Any news on this? There hasn't been a new release in over a year but the commits have been coming.

**Comment by kggiorno** [comment]
julio, it looks like github's been updated but not the pip install package 

xilni, you'll want to go to /users/<yourUser>/anaconda/lib/python3.4/site-packages/craigslist/ and rm the __init__.py file in there

replace it with the current __init__.py file julio has up on github:
https://raw.githubusercontent.com/juliomalegria/python-craigslist/master/craigslist/__init__.py
(I just copy pasted using vi)

**Comment by juliomalegria** [comment]
Sorry guys, I've been slacking off on this module. I'll review the pull requests & update the pip package tomorrow.
Thanks for all the collaboratioN!

**Comment by juliomalegria** [comment]
New version of python-craigslist (1.0.1) is live in PyPI now. That version should fix this issue.

Thanks for bearing with me :)
