### ISSUE TITLE
[question] Is there an easy way to fetch the images of a listing?

### ISSUE THREAD

**Issue by bevensteven** [juliomalegria/python-craigslist#96]
Sweet project!

After finding a bunch of listings, I'm wondering if there's a low-effort way to retrieve a listing's attached images? Can't think of anything off the top of my head other than scraping those images.

Thanks!

**Comment by irahorecka** [comment]
Yes, there is. Add keyword argument `include_details=True` when iterating through `get_results`. A list of image urls will be assigned to the key 'image' in the output value. 

`
# ...
for result in cl_h.get_results(sort_by='newest', geotagged=False, include_details=True):
    print(result['images'])
# ...
`

**Comment by juliomalegria** [comment]
Thanks @bevensteven for using the project. As @irahorecka pointed out, when getting the details of all posts (`include_details=TRue`), all URLs to images are included.

Thanks Ira for helping out!
