### ISSUE TITLE
geotagging failure due to None from fetch_content in base.py

### ISSUE THREAD

**Issue by Walid-Rahman2** [juliomalegria/python-craigslist#99]
Thanks for making this amazing package. I ran into some issues where if fetch_content returns a None, geotagging will fail. This breaks the collection of data. I assume the include details would also fail as a result. Can we have try except around geotagging and include details in the process row function? That way, the data collection process doesn't break. Thanks.

**Comment by irahorecka** [comment]
Hey @Walid-Rahman2 , could you provide a minimal reproducible code for this issue?

**Comment by juliomalegria** [comment]
Thanks @Walid-Rahman2 for reporting!
Indeed I see how the pipeline would break if `fetch_content` returned a `None` value. I've added a check to prevent this in ac666a2, and I'll be deploying a new PIP version later today.

**Comment by juliomalegria** [comment]
New version was release to PyPI 🙌
